server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nightmareydp/springcloud-config.git #GitHub上面的git仓库名字
          search-paths:
            - springcloud-config
      label: master

#服务注册到eureka地址z
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
